CREATE TABLE posts
(id INT, Title VARCHAR(150), 
DESCRIPTION VARCHAR(MAX), Author INT)

CREATE TRIGGER DEL_POST_TABLE ON DATABASE
FOR DROP_TABLE, ALTER_TABLE AS
PRINT 'You must disable Trigger
"DEL_POST_TABLE" to drop or alter tables!'
ROLLBACK