--CREATE INDEX SYTAX
--CREATE INDEX IX_SAL_INDEX ON salary(id)
--CREATE CLUSTERED INDEX CIX_PHONE_INDEX ON phone_records(P_ID)
--NON CLUSTERED INDEX
CREATE NONCLUSTERED INDEX NCIX_PHONE_INDEX ON phone_records(PersonName);

DROP INDEX NCIX_PHONE_INDEX ON phone_records