CREATE TABLE states_of_origin
(id INT PRIMARY KEY, states VARCHAR(50),
capital VARCHAR(50));

INSERT INTO states_of_origin VALUES
(1, 'Abia', 'Umuahia'),
(2, 'Adamawa', 'Yola'),
(3, 'Akwa Ibom', 'Uyo'),
(4, 'Anambra', 'Awka'),
(5, 'Bauchi', 'Bauchi'),
(6, 'Bayelsa', 'Yenagoa'),
(7, 'Benue', 'Makurdi'),
(8, 'Borno', 'Maiduguri'),
(9, 'Cross River', 'Calabar'),
(10, 'Delta', 'Asaba'),
(11, 'Ebonyi', 'Abakaliki'),
(12, 'Edo', 'Benin City'),
(13, 'Ekiti', 'Ado Ekiti'),
(14, 'Enugu', 'Enugu'),
(15, 'Gombe', 'Gombe'),
(16, 'Imo', 'Owerri'),
(17, 'Jigawa', 'Dutse'),
(18, 'Kaduna', 'Kaduna'),
(19, ' Kano ', 'Kano'),
(20, ' Katsina', 'Katsina'),
(21, 'Kebbi', 'Birnin Kebbi'),
(22, 'Kogi', 'Lokoja'),
(23, 'Kwara', 'Ilorin'),
(24, 'Lagos', 'Ikeja'),
(25, 'Nasarawa ', 'Lafia'),
(26, 'Niger', 'Minna'),
(27, 'Ogun', 'Abeokuta'),
(28, 'Ondo', 'Akure'),
(29, 'Osun', 'Osogbo'),
(30, 'Oyo', 'Ibadan'),
(31, 'Plateau', 'Jos'),
(32, 'Rivers', 'Port Harcourt'),
(33, 'Sokoto', 'Sokoto'),
(34, 'Taraba', 'Jalingo'),
(35, 'Yobe', 'Damaturu'),
(36, 'Zamfara', 'Gusau'),
(37, 'Federal Capital Territory (FCT)', 'Abuja');